trigger:
  - master

pool:
  vmImage: 'Ubuntu 18.04'

steps:
- task: GoTool@0
  inputs:
    version: '1.13.7'
    goBin: '$(Agent.HomeDirectory)/bin'

- script: GO111MODULE="on" go get sigs.k8s.io/kind@v0.7.0
  displayName: 'Install kind'

- script: $(GOBIN)/kind create cluster
  displayName: 'Deploying kind cluster'

- script: kubectl cluster-info --context kind-kind
  displayName: 'Show cluster info'
